# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ami_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('arn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keypair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('vpc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=20)),
                ('vpc', models.CharField(max_length=50)),
                ('keypair', models.CharField(max_length=50)),
                ('securitygroup', models.CharField(max_length=50)),
                ('ami', models.CharField(max_length=50)),
                ('userdata', models.CharField(blank=True, default='', max_length=500)),
                ('instancetype', models.CharField(max_length=20)),
                ('instance_profile', models.CharField(max_length=50)),
                ('public_ip', models.CharField(blank=True, default='', max_length=20)),
                ('max_spot', models.CharField(max_length=20)),
                ('request_id', models.CharField(default='null', max_length=20)),
                ('instance_id', models.CharField(default='null', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('status_code', models.CharField(default='null', max_length=20)),
                ('deleted', models.CharField(default='no', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpc_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
