# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50)),
                ('inter_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='null', max_length=50)),
                ('vid', models.CharField(max_length=50)),
            ],
        ),
    ]
