# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_eip_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='a_zone',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='volume',
            name='instance_id',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='volume',
            name='snap_id',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='volume',
            name='state',
            field=models.CharField(default='available', max_length=50),
        ),
    ]
